In [5]:
import pandas as pd

xls = pd.ExcelFile("./data/netflix_user_behavior_dataset.xlsx")
print(xls.sheet_names)

dataset = pd.read_excel(xls, "dataset")
dataset.to_csv("./data/netflix.csv", index=False)

['netflix_user_behavior_dataset', 'dataset', 'gender', 'country', 'subscription_type', 'payment_method', 'primary_device', 'favorite_genre', 'churned']

In [6]:
df = pd.read_csv("./data/netflix.csv")

df = df.drop(columns=["user_id"])
df.head()

,age,gender,country,account_age_months,subscription_type,monthly_fee,payment_method,primary_device,devices_used,favorite_genre,avg_watch_time_minutes,watch_sessions_per_week,binge_watch_sessions,completion_rate,rating_given,content_interactions,recommendation_click_rate,days_since_last_login,churned
0,56,1,1,17,1,15.99,1,1,1,1,220,17,3,60,1.7,5,66,16,0
1,46,2,2,20,1,12.99,1,2,2,2,76,15,4,71,4.6,7,78,14,0
2,32,3,2,25,2,15.99,1,2,2,3,215,6,13,33,2.0,27,29,41,0
3,60,1,3,37,1,12.99,1,3,3,4,280,4,9,58,1.2,9,23,22,0
4,25,1,4,23,3,12.99,1,4,3,5,261,15,9,64,1.3,49,56,54,0

In [7]:
df.isnull().sum()

age                          0
gender                       0
country                      0
account_age_months           0
subscription_type            0
monthly_fee                  0
payment_method               0
primary_device               0
devices_used                 0
favorite_genre               0
avg_watch_time_minutes       0
watch_sessions_per_week      0
binge_watch_sessions         0
completion_rate              0
rating_given                 0
content_interactions         0
recommendation_click_rate    0
days_since_last_login        0
churned                      0
dtype: int64

In [9]:
df["engagement"] = df["watch_sessions_per_week"] * df["avg_watch_time_minutes"]
df["is_active"] = df["days_since_last_login"] < 15
df["binge_ratio"] = df["binge_watch_sessions"] / df["watch_sessions_per_week"]
df["interaction_score"] = df["content_interactions"] * df["recommendation_click_rate"]
df["account_age_years"] = df["account_age_months"] / 12
df.head()

,age,gender,country,account_age_months,subscription_type,monthly_fee,payment_method,primary_device,devices_used,favorite_genre,...,rating_given,content_interactions,recommendation_click_rate,days_since_last_login,churned,engagement,is_active,binge_ratio,interaction_score,account_age_years
0,56,1,1,17,1,15.99,1,1,1,1,...,1.7,5,66,16,0,3740,False,0.176471,330,1.416667
1,46,2,2,20,1,12.99,1,2,2,2,...,4.6,7,78,14,0,1140,True,0.266667,546,1.666667
2,32,3,2,25,2,15.99,1,2,2,3,...,2.0,27,29,41,0,1290,False,2.166667,783,2.083333
3,60,1,3,37,1,12.99,1,3,3,4,...,1.2,9,23,22,0,1120,False,2.250000,207,3.083333
4,25,1,4,23,3,12.99,1,4,3,5,...,1.3,49,56,54,0,3915,False,0.600000,2744,1.916667

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = df.drop("churned", axis=1)
y = df["churned"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)

df["prediction"] = model.predict(X)
df.head(20)

,age,gender,country,account_age_months,subscription_type,monthly_fee,payment_method,primary_device,devices_used,favorite_genre,...,content_interactions,recommendation_click_rate,days_since_last_login,churned,engagement,is_active,binge_ratio,interaction_score,account_age_years,prediction
0,56,1,1,17,1,15.99,1,1,1,1,...,5,66,16,0,3740,False,0.176471,330,1.416667,0
1,46,2,2,20,1,12.99,1,2,2,2,...,7,78,14,0,1140,True,0.266667,546,1.666667,0
2,32,3,2,25,2,15.99,1,2,2,3,...,27,29,41,0,1290,False,2.166667,783,2.083333,0
3,60,1,3,37,1,12.99,1,3,3,4,...,9,23,22,0,1120,False,2.250000,207,3.083333,0
4,25,1,4,23,3,12.99,1,4,3,5,...,49,56,54,0,3915,False,0.600000,2744,1.916667,0
5,38,2,5,23,1,12.99,1,2,2,2,...,15,36,18,0,1012,False,0.090909,540,1.916667,0
6,56,3,4,11,2,15.99,2,2,1,2,...,45,46,2,0,999,True,1.333333,2070,0.916667,0
7,36,3,6,46,1,15.99,1,4,3,1,...,42,35,59,0,2930,False,0.200000,1470,3.833333,0
8,40,2,6,20,2,12.99,2,1,2,6,...,15,24,31,0,1414,False,1.285714,360,1.666667,0
9,28,2,7,7,3,15.99,3,4,2,4,...,11,17,31,1,492,False,2.500000,187,0.583333,1
10,28,2,4,23,1,12.99,2,4,1,1,...,22,80,7,0,792,True,0.222222,1760,1.916667,0
11,41,3,5,23,2,12.99,4,3,2,6,...,28,40,40,0,546,False,3.333333,1120,1.916667,0
12,53,1,6,27,1,7.99,3,4,1,2,...,12,43,0,1,756,True,0.277778,516,2.250000,1
13,57,2,7,21,1,7.99,3,3,1,2,...,6,67,12,0,884,True,0.384615,402,1.750000,0
14,41,2,8,21,2,12.99,3,4,2,4,...,21,77,16,1,1500,False,0.400000,1617,1.750000,1
15,20,1,9,58,1,15.99,2,4,2,2,...,7,53,19,0,294,False,3.000000,371,4.833333,0
16,39,1,1,32,3,7.99,1,1,2,7,...,16,60,32,0,2115,False,0.066667,960,2.666667,0
17,19,3,3,50,1,7.99,2,2,2,6,...,39,10,33,0,1540,False,0.100000,390,4.166667,0
18,41,2,4,28,1,7.99,2,3,3,3,...,15,86,16,0,4161,False,0.105263,1290,2.333333,0
19,61,3,2,37,2,7.99,4,2,1,3,...,34,86,42,0,320,False,0.437500,2924,3.083333,0

In [13]:
df["churned"].value_counts(normalize=True)

churned
0    0.80072
1    0.19928
Name: proportion, dtype: float64

In [14]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(class_weight="balanced", random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [15]:
df["low_activity"] = df["watch_sessions_per_week"] < 5
df["inactive_user"] = df["days_since_last_login"] > 30

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X = df.drop("churned", axis=1)
y = df["churned"]

# encoding
X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    class_weight="balanced",
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', max_depth=12, n_estimators=300,
                       random_state=42)

In [19]:
preds = model.predict(X_test)

import pandas as pd
pd.Series(preds).value_counts()

0    8024
1    1976
Name: count, dtype: int64

In [20]:
from sklearn.metrics import classification_report

print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8007
           1       1.00      0.99      1.00      1993

    accuracy                           1.00     10000
   macro avg       1.00      1.00      1.00     10000
weighted avg       1.00      1.00      1.00     10000

In [22]:
df.corr()

,age,gender,country,account_age_months,subscription_type,monthly_fee,payment_method,primary_device,devices_used,favorite_genre,...,days_since_last_login,churned,engagement,is_active,binge_ratio,interaction_score,account_age_years,prediction,low_activity,inactive_user
age,1.000000,-0.007493,-0.000960,-0.003321,-0.000881,-0.001249,0.005220,-0.001841,0.003628,0.005392,...,0.002316,-0.002417,-0.002494,-0.001231,-0.005157,-0.004984,-0.003321,-0.002584,0.003721,0.000551
gender,-0.007493,1.000000,-0.000573,0.001923,0.000293,0.003103,0.003509,0.000253,-0.004353,-0.009862,...,-0.006031,0.007211,-0.004933,0.006928,0.004416,0.004562,0.001923,0.006964,0.005008,-0.008895
country,-0.000960,-0.000573,1.000000,-0.000390,-0.006897,-0.001772,-0.006522,0.000674,0.002021,-0.009971,...,0.001808,-0.001041,0.001959,-0.002107,0.003636,-0.001650,-0.000390,-0.001027,0.001529,0.001970
account_age_months,-0.003321,0.001923,-0.000390,1.000000,-0.000036,0.002198,0.000750,0.000688,-0.002959,0.007346,...,0.002224,-0.006852,-0.013809,-0.004155,0.010656,-0.000351,1.000000,-0.006347,0.008834,0.003066
subscription_type,-0.000881,0.000293,-0.006897,-0.000036,1.000000,-0.002610,-0.002611,0.000850,-0.001205,-0.004539,...,-0.002120,0.002320,-0.002334,-0.000743,0.001023,-0.001362,-0.000036,0.002138,-0.004199,-0.002846
monthly_fee,-0.001249,0.003103,-0.001772,0.002198,-0.002610,1.000000,-0.002279,0.004913,0.005897,-0.005567,...,-0.004023,-0.006194,0.001967,0.005289,0.009575,-0.003728,0.002198,-0.006660,0.004037,-0.004272
payment_method,0.005220,0.003509,-0.006522,0.000750,-0.002611,-0.002279,1.000000,-0.002212,-0.008933,0.006675,...,0.001220,0.001716,0.002169,-0.002216,0.001188,0.004481,0.000750,0.001982,0.002661,0.003013
primary_device,-0.001841,0.000253,0.000674,0.000688,0.000850,0.004913,-0.002212,1.000000,-0.005835,-0.001551,...,0.002061,-0.002166,-0.000913,-0.002303,0.002392,0.001723,0.000688,-0.002470,0.003519,0.005933
devices_used,0.003628,-0.004353,0.002021,-0.002959,-0.001205,0.005897,-0.008933,-0.005835,1.000000,0.001980,...,0.007411,0.002238,0.006901,-0.008248,0.003631,0.001037,-0.002959,0.002118,0.003055,0.007174
favorite_genre,0.005392,-0.009862,-0.009971,0.007346,-0.004539,-0.005567,0.006675,-0.001551,0.001980,1.000000,...,0.002045,0.001441,-0.000621,-0.005220,0.004345,-0.002306,0.007346,0.001440,0.002713,0.003407
avg_watch_time_minutes,0.002986,-0.004538,0.003177,-0.006862,-0.001828,0.003458,0.003083,0.001345,0.013087,-0.000894,...,0.003144,-0.005022,0.653415,-0.001363,0.003774,0.004454,-0.006862,-0.005554,0.006667,0.000663
watch_sessions_per_week,-0.003903,0.000071,0.001756,-0.013159,-0.000618,-0.005715,-0.001033,-0.004120,-0.002001,-0.003256,...,0.006993,-0.003505,0.663672,-0.009778,-0.556095,-0.004628,-0.013159,-0.004196,-0.709713,0.004010
binge_watch_sessions,-0.001585,-0.001694,0.000600,-0.000585,0.003744,0.004547,-0.005321,-0.002268,-0.001009,-0.000164,...,0.000527,-0.003292,0.002555,-0.000379,0.406005,0.001099,-0.000585,-0.003185,-0.005466,0.002645
completion_rate,0.001884,0.000090,0.002865,0.006694,0.005064,0.003470,-0.000707,-0.001663,-0.009371,-0.000469,...,-0.001558,-0.001839,-0.002869,-0.003339,0.010046,0.000517,0.006694,-0.002272,0.010161,-0.002324
rating_given,-0.000391,0.002640,0.002357,-0.001006,0.007379,0.002812,0.000816,0.002139,0.006082,0.001133,...,-0.005846,0.003255,0.005744,0.001233,-0.008528,0.006517,-0.001006,0.003440,0.000619,-0.006784
content_interactions,-0.003516,-0.000291,-0.001551,-0.001570,-0.000769,-0.001833,0.002771,0.001821,-0.003282,-0.000895,...,-0.001302,-0.006720,-0.003337,-0.003400,0.005629,0.656697,-0.001570,-0.007088,0.004841,-0.003672
recommendation_click_rate,-0.005728,0.006584,0.001480,-0.002141,0.000830,-0.004925,-0.000667,0.001117,-0.002793,0.002528,...,-0.006101,-0.002262,-0.001025,0.002986,0.007485,0.644659,-0.002141,-0.003039,0.001327,-0.004947
days_since_last_login,0.002316,-0.006031,0.001808,0.002224,-0.002120,-0.004023,0.001220,0.002061,0.007411,0.002045,...,1.000000,0.000453,0.010977,-0.748130,-0.001611,-0.004251,0.002224,0.000948,-0.006571,0.865365
churned,-0.002417,0.007211,-0.001041,-0.006852,0.002320,-0.006194,0.001716,-0.002166,0.002238,0.001441,...,0.000453,1.000000,-0.006591,-0.001153,-0.006211,-0.005400,-0.006852,0.994607,0.000006,-0.000072
engagement,-0.002494,-0.004933,0.001959,-0.013809,-0.002334,0.001967,0.002169,-0.000913,0.006901,-0.000621,...,0.010977,-0.006591,1.000000,-0.011035,-0.368558,-0.001332,-0.013809,-0.007298,-0.470686,0.006717
is_active,-0.001231,0.006928,-0.002107,-0.004155,-0.000743,0.005289,-0.002216,-0.002303,-0.008248,-0.005220,...,-0.748130,-0.001153,-0.011035,1.000000,-0.000307,-0.000620,-0.004155,-0.001556,0.006613,-0.555588
binge_ratio,-0.005157,0.004416,0.003636,0.010656,0.001023,0.009575,0.001188,0.002392,0.003631,0.004345,...,-0.001611,-0.006211,-0.368558,-0.000307,1.000000,0.005453,0.010656,-0.005667,0.602952,0.000477
interaction_score,-0.004984,0.004562,-0.001650,-0.000351,-0.001362,-0.003728,0.004481,0.001723,0.001037,-0.002306,...,-0.004251,-0.005400,-0.001332,-0.000620,0.005453,1.000000,-0.000351,-0.006286,0.003579,-0.004896
account_age_years,-0.003321,0.001923,-0.000390,1.000000,-0.000036,0.002198,0.000750,0.000688,-0.002959,0.007346,...,0.002224,-0.006852,-0.013809,-0.004155,0.010656,-0.000351,1.000000,-0.006347,0.008834,0.003066
prediction,-0.002584,0.006964,-0.001027,-0.006347,0.002138,-0.006660,0.001982,-0.002470,0.002118,0.001440,...,0.000948,0.994607,-0.007298,-0.001556,-0.005667,-0.006286,-0.006347,1.000000,0.000655,0.000660
low_activity,0.003721,0.005008,0.001529,0.008834,-0.004199,0.004037,0.002661,0.003519,0.003055,0.002713,...,-0.006571,0.000006,-0.470686,0.006613,0.602952,0.003579,0.008834,0.000655,1.000000,-0.005718
inactive_user,0.000551,-0.008895,0.001970,0.003066,-0.002846,-0.004272,0.003013,0.005933,0.007174,0.003407,...,0.865365,-0.000072,0.006717,-0.555588,0.000477,-0.004896,0.003066,0.000660,-0.005718,1.000000

In [23]:
print(X.columns)

Index(['age', 'gender', 'country', 'account_age_months', 'subscription_type',
       'monthly_fee', 'payment_method', 'primary_device', 'devices_used',
       'favorite_genre', 'avg_watch_time_minutes', 'watch_sessions_per_week',
       'binge_watch_sessions', 'completion_rate', 'rating_given',
       'content_interactions', 'recommendation_click_rate',
       'days_since_last_login', 'engagement', 'is_active', 'binge_ratio',
       'interaction_score', 'account_age_years', 'prediction', 'low_activity',
       'inactive_user'],
      dtype='str')

In [ ]:
df = df.drop(columns=["prediction"])
X = df.drop("churned", axis=1)
y = df["churned"]
x = pd.get_dummies(X, drop_first=True)

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = RandomForestClassifier(
    class_weight="balanced",
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [26]:
from sklearn.metrics import classification_report

preds = model.predict(X_test)

print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      8007
           1       0.00      0.00      0.00      1993

    accuracy                           0.80     10000
   macro avg       0.40      0.50      0.44     10000
weighted avg       0.64      0.80      0.71     10000

c:\Users\geral\miniconda3\envs\netflix_env\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\geral\miniconda3\envs\netflix_env\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\geral\miniconda3\envs\netflix_env\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])